sudo: required

language: cpp

compiler: 
  - gcc

before_install:
  - sudo apt-get update
  - sudo apt-get install -qq valgrind
  - sudo apt-get install cxxtest

script:
  - gcc --version
  - bash execute.sh
  - make
  - valgrind --leak-check=full ./tp
