sudo: required

language: cpp

compiler: 
  - gcc

env:
  global:
    - ROOT_PATH=$(pwd)
    - PROJECT_PATH=$ROOT_PATH/project
    - TEST_CASES_PATH=$ROOT_PATH/test_cases
    - CXX_TEST_PATH=$ROOT_PATH/cxxtest

before_install:
  - sudo apt-get update
  - sudo apt-get install -qq valgrind
  - sudo apt-get install cxxtest

script:
  - cd $PROJECT_PATH 
  - bash execute.sh
  - make
  - valgrind --leak-check=full ./tp
  - cd $TEST_CASES_PATH
  - cxxtestgen --error-printer -o runner.cpp my_test_cases.h
  - g++ -o runner runner.cpp
  - ./runner
