sudo: required

language: cpp

compiler: 
  - gcc

env:
  global:
    - PROJECT_PATH=./project
    - TEST_CASES_PATH=./test_cases
    - CXX_TEST_PATH=./cxxtest

before_install:
  - sudo apt-get update
  - sudo apt-get install -qq valgrind
  - sudo apt-get install cxxtest

script:
  - cd $PROJECT_PATH 
  - bash execute.sh
  - make
  - valgrind --leak-check=full ./tp
  - cd $TEST_CASES_PATH
  - cxxtestgen 
