version: "3"
services:
   worms-server:
      image: worms-taller-party:0.2
      networks:
         worms-taller-party-net:
            ipv4_address: 172.19.2.2
      ports:
         - '18080:8080'
      hostname: worms
      domainname: docker_worms
      volumes:
         - /tmp/.X11-unix:/tmp/.X11-unix
      command: 'worms-server 8080'
networks:
   worms-taller-party-net:
      driver: bridge
      ipam:
         driver: default
         config:
            - subnet: 172.19.2.0/29